include:
  - proxy.yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: dio-web
    restart: on-failure
    environment:
      - DB_HOST=172.20.0.10
      - DB_USER=dio
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=dio-db
    networks:
      backend:
        ipv4_address: 172.20.0.5
    depends_on:
      - reverse-proxy
      - ingress-proxy
      - db
    env_file:
      - .env
  db:
    image: mysql:8
    container_name: dio-mysql
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.10
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=dio-db
      - MYSQL_USER=dio
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
    depends_on:    
      - reverse-proxy
      - ingress-proxy
    env_file:
      - .env
