include:
  - proxy.yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: dio-web
    restart: on-failure
    environment:
      - DB_HOST=<MYSQL_HOST_FROM_TERRAFORM>
      - DB_NAME=<MYSQL_DATABASE_FROM_TERRAFORM>
      - DB_USER=<MYSQL_USER_FROM_TERRAFORM>
      - DB_PASSWORD=<MYSQL_PASSWORD_FROM_TERRAFORM>
    networks:
      backend:
        ipv4_address: 172.20.0.5
    ports:
      - 5000:5000
    depends_on:
      - reverse-proxy
      - ingress-proxy
      - db
    env_file:
      - .env
      
  db:
    image: mysql:8
    container_name: dio-mysql
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.10
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
    depends_on:    
      - reverse-proxy
      - ingress-proxy
    env_file:
      - .env
